#!/bin/bash
# Hook: lint the file Claude just edited.
# Fires on: PostToolUse (Edit/Write)
# Delegates to: .claude/hooks/on-edit-lint.sh (generated by Claude for your stack)

INPUT=$(cat)
FILE=$(echo "$INPUT" | grep -oP '"path"\s*:\s*"\K[^"]+(?=")' | head -1)

LINT_HOOK=".claude/hooks/on-edit-lint.sh"

if [ ! -f "$LINT_HOOK" ]; then
  echo "⚠️  Stack hooks not set up yet." >&2
  echo "   Tell Claude: 'set up the quality hooks for this project'" >&2
  exit 0
fi

bash "$LINT_HOOK" "$FILE"
exit $?
