#!/bin/bash
# Hook: run full lint + tests before Claude declares the task complete.
# Fires on: Stop event
# Delegates to: .claude/hooks/run-lint.sh and .claude/hooks/run-tests.sh
# (both generated by Claude for your specific stack)

LINT_HOOK=".claude/hooks/run-lint.sh"
TEST_HOOK=".claude/hooks/run-tests.sh"

if [ ! -f "$LINT_HOOK" ] || [ ! -f "$TEST_HOOK" ]; then
  echo "⚠️  Stack hooks not configured — quality gate skipped." >&2
  echo "   Tell Claude: 'set up the quality hooks for this project'" >&2
  exit 0
fi

echo "=== Quality Gate ===" >&2

echo "Running lint..." >&2
LINT_OUTPUT=$(bash "$LINT_HOOK" 2>&1)
LINT_EXIT=$?
echo "$LINT_OUTPUT" >&2

if [ $LINT_EXIT -ne 0 ]; then
  echo "QUALITY GATE FAILED: Lint errors found. Fix all errors before declaring done."
  exit 2
fi

echo "Running tests..." >&2
TEST_OUTPUT=$(bash "$TEST_HOOK" 2>&1)
TEST_EXIT=$?
echo "$TEST_OUTPUT" >&2

if [ $TEST_EXIT -ne 0 ]; then
  echo "QUALITY GATE FAILED: Tests failed. Fix all failures before declaring done."
  exit 2
fi

echo "✅ Quality gate passed." >&2
exit 0
